uw-midsun/firmware

Makefile
libraries/stm32f0xx/inc/retarget.h
libraries/stm32f0xx/src/retarget.c
libraries/stm32f0xx/src/startup_stm32f0xx.s
libraries/unity/inc/unity_internals.h
make/build.mk
make/build_test.mk
platform/stm32f0xx/platform.mk
platform/x86/platform.mk

Currently redirects stdout to semihosting - once we receive UART to USB adapters, I'll switch it to UART.
I found that if you include stdio.h, putchar is defined as both a function and a macro, and that macro overrides the function declaration with an inlined function that doesn't work. For unity, I undefined the macro. For everything else, just don't use putchar. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uw-midsun/firmware/11)

ELEC-36: Retarget STDOUT on STMF0xx

---

LICENSE
README.md

Update README.md with Travis CI badge, and some more details about
how to get started. There's a bit about how our build system works. Added
MIT software LICENSE.

ELEC-56: Update README and add MIT LICENSE

---

lint.py

Update so comments such as
bool ok = true: // Sets ok to true.
Are valid with a single space rather than needing two spaces. 
Updated submodules.

ELEC-40 Updated comment rules in linter and submodules

---

.travis.yml

Currently Travis CI is configured to build on every **push**, and every **pull** request (running tests as if the PR is merged). This isn't great, since disabling Travis for push requests via the settings means that tests against the master branch are not run whenever PRs are merged.
This change configures Travis so that it builds against every merge into **master** (a **push** request, since we never push directly to master) and on every PR (a **pull** request).

ELEC-60: Configure Travis to build PRs and master

---

.travis.yml
Makefile
make/build_test.mk
platform/stm32f0xx/platform.mk
platform/x86/platform.mk

Added ability to specify a unit test to run with `TEST=`. Requires `LIBRARY` or `PROJECT` to be defined.
Also fixed `make test` running all tests.

ELEC-79: Added test specifier for unit tests

---

lint.py

Allows for "weird" (1 or 3) space indentation when continuing a macro. 
Example this is now ok:
`#define MY_MACRO() \`
`___foo()`
NOTE: _ is a space it won't render on here correctly.
MERGE BEFORE #23

ELEC-40 Added support for macro line continuation spacing variance.

---

platform/stm32f0xx/platform.mk

Fixed a typo where SEMIHOSTING in platform.mk for stm32f0xx should have read SEMIHOSTING_ENABLED. This now allows semihosting to work.

ELEC-36 Fixed a bug/typo that caused Semihosting to not enable.

---

libraries/ms-common/inc/gpio.h
libraries/ms-common/inc/status.h
libraries/ms-common/src/status.c
libraries/ms-common/src/stm32f0xx/gpio.c
libraries/ms-common/src/x86/gpio.c

Trivial change that specifies void arguments for a few functions I wrote in C++ style not knowing any better.

ELEC-95 Specify void as arg for some functions.

---

.gitignore
Makefile
README.md
platform/x86/platform.mk

Added support and documentation for optionally using clang instead of gcc on x86. This adds support for memory sanitization, leak checking and stack traces via ASAN and race condition checks via TSAN. Also added documentation on using Build EAR and clang-tidy for static analysis.
For users uninterested in these features they are entirely opt-in, there is no change to the existing build workflow and no additional downloads are needed to keep working as you have been. They simply make my life easier when writing x86 code. 
Added variables to the x86 paltform.mk for `COMPILER= [gcc | clang] COPTIONS = [asan | tsan]`. gcc without options remains the default.
@karlding I'll leave it up to you whether or not to change/add a Travis CI check for x86 tests that builds with ASAN enabled. This would …

ELEC-111 Clang Tools Support

---

libraries/ms-common/inc/gpio.h
libraries/x86/src/x86_interrupt.c

Calling getpid() from a thread other than the main thread would result in an incorrect software interrupt trigger. To resolve this issue a static pid should be recorded from the initializing thread.
Update gpio.h docs.

ELEC-116 x86_interrupt bug fix.

---

.travis.yml

Replace ``-qq`` flag with ``-y``.
```
-qq No output except for errors
```
Travis is killing the job due to installs taking more than 10 minutes. Since `qq` suppresses all output, no output is produced, and Travis will kill any job with [no log output produced](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts).

ELEC-153: Remove qq flag from GCC ARM install step

---

Makefile
README.md
make/build_test.mk
platform/stm32f0xx/platform.mk
platform/stm32f0xx/scripts/gdb_flash
platform/stm32f0xx/scripts/stm32f0-openocd.cfg
platform/x86/platform.mk

Adds support for our ST-Link clones running the dap42 firmware and cleans up test handling a lot. Uses the CMSIS-DAP probe by default - to use with an stlink, add `PROBE=stlink-v2`.
Serial support is still a TODO - I wasn't able to pass the serial port through to my VM properly. @ckitagawa, can you let me know what setup you ended up using to receive serial data?

ELEC-143: CMSIS-DAP support

---

Makefile
platform/stm32f0xx/platform.mk

`GDB_TARGET` was being evaluated before `PLATFORM_EXT` was assigned. Switched to lazy evaluation to fix it.

ELEC-160: Fixed GDB target

---

libraries/ms-common/inc/fsm.h
libraries/ms-common/inc/fsm_impl.h
libraries/ms-common/src/fsm.c
libraries/ms-common/test/test_fsm.c

Adds support for basic FSM transition guards. I haven't fully fleshed out what information guards should have, but I'd like to limit them to the minimum.

ELEC-200: Added FSM transitions

---

libraries/CMSIS/rules.mk
libraries/STM32F0xx_StdPeriph_Driver/rules.mk
libraries/ms-common/rules.mk
libraries/stm32f0xx/rules.mk
libraries/unity/rules.mk
libraries/x86/rules.mk
make/build.mk
make/build_test.mk
project/README.md
project/plutus/rules.mk
project/queue/rules.mk
project/test_project/rules.mk

Supports filtering out tests. I plan on using this to exclude tests by checking for the current platform and defining `$(T)_EXCLUDE_TESTS := can can_rx ...`.

ELEC-159: Support excluding tests per-platform

---

libraries/ms-common/inc/adc.h
libraries/ms-common/inc/can.h
libraries/ms-common/inc/can_ack.h
libraries/ms-common/inc/can_hw.h
libraries/ms-common/inc/delay.h
libraries/ms-common/inc/gpio_it.h
libraries/ms-common/inc/soft_timer.h
libraries/ms-common/inc/spi.h
libraries/ms-common/inc/uart.h
libraries/ms-common/src/stm32f0xx/can_hw.c
libraries/ms-common/test/test_can_hw.c

Turns out most modules just rely on interrupts, GPIO, and soft timers to be initialized.
I also switched CAN to use the interrupt module.

ELEC-219: Added module dependencies

---

libraries/STM32F0xx_StdPeriph_Driver/inc/stm32f0xx_interrupt.h
libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_interrupt.c
libraries/libcore/inc/status.h
libraries/ms-common/inc/can_hw.h
libraries/ms-common/inc/critical_section.h
libraries/ms-common/inc/delay.h
libraries/ms-common/inc/event_queue.h
libraries/ms-common/inc/fsm.h
libraries/ms-common/inc/gpio.h
libraries/ms-common/inc/gpio_it.h
libraries/ms-common/inc/interrupt.h
libraries/ms-common/inc/log.h
libraries/ms-common/inc/spi.h
libraries/ms-common/inc/test_helpers.h
libraries/ms-common/inc/wait.h
libraries/ms-common/src/stm32f0xx/gpio.c
libraries/ms-common/src/stm32f0xx/gpio_it.c
libraries/ms-common/src/stm32f0xx/spi.c
libraries/ms-common/src/x86/gpio.c
libraries/ms-common/src/x86/gpio_it.c
libraries/ms-common/src/x86/spi.c
libraries/ms-common/test/test_gpio_it.c
libraries/x86/inc/x86_interrupt.h
libraries/x86/src/x86_interrupt.c

This PR is the first in what will likely be a series of PRs that cleanup the ms-common library prior to the start of the new term.
**Issues addressed in this PR:**
*   "Const Correctness" --- adding the const modifier to places where it is applicable especially in interfaces.
*   Documentation in `*.h` files is lacking in some places. I also fixed any spelling or grammatical errors I found. This is likely to be an ongoing project.
**Issues to consider in a future PR:**
*   Move generic data structures such as objpool, queues and FSM to libcore.
*   Move other generic code such as log to libcore. 
Moving things to libcore will entail keeping their tests in ms-common or in a new library of just tests for libcore. This is because the tests need to be built after the platform libs are built …

ELEC-259: Documentation Improvements and Const Correctness in Interfaces

---

libraries/ms-common/inc/pwm.h
libraries/ms-common/inc/stm32f0xx/pwm_mcu.h
libraries/ms-common/inc/x86/pwm_mcu.h
libraries/ms-common/rules.mk
libraries/ms-common/src/delay.c
libraries/ms-common/src/stm32f0xx/pwm.c
libraries/ms-common/src/x86/pwm.c
libraries/ms-common/test/test_pwm.c

This is a relatively simple PR to remove the restriction that `TIM3` is the only timer that can be used on the stm32f0xx architecture for PWM output. ~~I plan to manually perform functional testing for all 6 timers supporting PWM output this afternoon I just wanted to put this up for PR ahead of time.~~ (DONE). Currently, nothing depends on PWM so it would be nice to get this API change in before anything starts relying on it.

ELEC-263: Improve PWM module by supporting different hardware timers.

---

libraries/ms-common/inc/can_pack_impl.h
libraries/ms-common/inc/can_unpack_impl.h
libraries/ms-common/src/can_pack_impl.c
libraries/ms-common/src/can_unpack_impl.c
libraries/ms-common/test/test_can_pack_impl.c
libraries/ms-common/test/test_can_unpack_impl.c

This PR is the backend (firmware) component of the work required for ELEC-274 which will add templates to codegen to automatically generate boilerplate macros for each message to pack, unpack and transmit using verbose field/message names and automatically masking and populating the message id, source id and type fields. The reason these are `*_impl` is because they are internals that should not be called in modules other than `can_pack` and `can_unpack` which will be generate by templates.
CAN pack is very straightforward other than the fact that the `dlc` field is set to the minimum required bytes to convey the message. This means if the last fields are 0s they will not be sent. However, since we are using codegen this isn't an issue in determining how large the data field is since when …

ELEC-276: CAN Pack and Unpack implementations

---

libraries/libcore/inc/misc.h
libraries/ms-common/inc/can_ack.h
libraries/ms-common/src/can_ack.c
libraries/ms-common/test/test_can.c
libraries/ms-common/test/test_can_ack.c

Switched from `num_expected` to expected device bitset.
Added variadic macro `CAN_ACK_EXPECTED_DEVICES(...)` to reduce the number of macros we need. I figure people will get confused and use the wrong macro.

ELEC-280: CAN ACK device bitset

---

.travis.yml
README.md

* Pin `gcc-arm-none-eabi-6-2017-q2-update`
* Speed up builds by caching
* Speed up builds by removing parallel jobs

ELEC-313: Speed up Travis CI builds

---

libraries/ms-common/src/x86/can_hw.c

Previous implementation would attempt to lock and die if the lock failed, resulting in contention between the TX and RX thread.
1. Thread A trylock: success
2. Thread B trylock: fail
3. Thread B exit
4. Thread A unlock
5. Thread B is dead, test hangs
Now locks the mutex at the beginning so trylocks should fail.

ELEC-303: Reversed CAN HW mutex logic to fix race condition

---

projects/chaos/inc/chaos_events.h
projects/chaos/inc/power_path.h
projects/chaos/rules.mk
projects/chaos/src/power_path.c
projects/chaos/test/test_power_path.c

This is an implementation of the "driver" for the power path IC. Essentially this boils down to two main purposes:
-  Monitor the UV and OV pin which signals when an over or under voltage occurs by raising an event. This event will be handled by a CAN FSM which will send the message to Telemetry/Driver Display.
- Read values using the ADCs periodically for current and voltage of both the Aux Battery and DCDCs. It is possible to request the latest data at any time. I will add a hook later to send a CAN message with this info to telemetry each time it updates.
I also exposed an API to disable monitoring to avoid errors when turning off the DCDCs.
Tested manually on STM32F0xx and passed. x86 test fails as the ADC driver is unimplemented.

ELEC-105: Chaos Power Path implementation

---

Makefile
libraries/ms-common/inc/can_hw.h
libraries/ms-common/src/can.c
libraries/ms-common/src/can_fsm.c
libraries/ms-common/src/stm32f0xx/can_hw.c
libraries/ms-common/src/x86/can_hw.c
libraries/ms-common/test/test_can_hw.c

Adds extended ID support to CAN HW. This will be used for CAN <-> UART interfaces.
Also fixes clang-format not using our format file.

ELEC-305: CAN Extended ID Support 

---

libraries/ms-common/inc/spi.h
libraries/ms-common/src/stm32f0xx/spi.c

I was using ffs when I should've been using clz. Now properly calculates a reasonable prescaler.
Note that there a limited number of supported baudrates - i.e. 1MHz will actually be 48MHz/32 = 1.5MHz. I was thinking of just making those enums so it's more clear, but it's dependent on our PCLK frequency.

ELEC-328: Fixed SPI prescaler

---

projects/chaos/inc/chaos_events.h
projects/chaos/inc/power_path.h
projects/chaos/src/power_path.c
projects/chaos/test/test_power_path.c

This is the first in a multi-part series of PRs to merge the contents of `elec_105_chaos_can` into `master`.
This PR does the following:
- Changes errors from raising events to publishing CAN events
- Fills in the `chaos_events.h` file
- Updates the test for `power_path`
- Adds an alternative interface to the Power Path API that uses events to make changes (all other modules in Chaos will share the same interface to allow them to all hook into the main event loop)

ELEC-105: [Chaos] Finished Power Path API

---

libraries/libcore/inc/status.h
libraries/libcore/src/status.c
libraries/ms-common/inc/gpio_it.h
libraries/ms-common/inc/objpool.h
libraries/ms-common/src/objpool.c
libraries/ms-common/src/stm32f0xx/gpio_it.c
libraries/ms-common/src/x86/gpio_it.c
libraries/ms-helper/inc/debouncer.h
libraries/ms-helper/src/debouncer.c
libraries/x86/inc/x86_interrupt.h
libraries/x86/src/x86_interrupt.c

Unifies the callback declaration style across libraries and projects that we own to be CamelCase.
This was done using the following method:
Find the type definitions using:
```bash
$ rg 'typedef .* ('
```
[rg](https://github.com/BurntSushi/ripgrep)
Fix using `sed` to (don't run in directory with `.git` or it will corrupt the log):
```bash
$ find . -type -exec sed -i 's/<before>/<after>/g' {} +
```
For now acronyms will remain the `UPPERCASE` style until that can be hopefully fixed with `clang-rename`.

ELEC-321: LSC Unify Callback Style

---

libraries/codegen-tooling/inc/can_pack.h
libraries/codegen-tooling/inc/can_transmit.h
libraries/codegen-tooling/inc/can_unpack.h
libraries/codegen-tooling/version.txt
make/git_fetch.py

* Roll codegen-tooling forward to latest release (v0.0.6)
* Force `curl` to use `curl` User-Agent and not whatever is specified in ~/.curlrc
Not sure if we want the second change, but I was running into an issue where I had the following set in my `~/.curlrc` file
```
user-agent = "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)"
connect-timeout = 60
referer = ";auto"
show-error
```
And because my User-Agent string doesn't contain `curl`, GitHub seems to minify the  JSON response. I've basically fixed this by forcing the User-Agent to be `curl`, but maybe that's the wrong approach?
Here's the JSON response _without_ `curl` in the header
```
→ TITANIC@firmware (elec_128_update_codegen_tooling) $ curl -s https://api.github.com/repos/uw-midsun/codegen-tooling/releases/latest …
```

ELEC-128: Roll codegen-tooling forward to latest (v0.0.6)

---

.clang-format
libraries/libcore/src/status.c
libraries/ms-common/inc/soft_timer.h
libraries/ms-common/test/test_gpio_it.c
libraries/stm32f0xx/inc/stm32f0xx_conf.h
libraries/x86/inc/x86_interrupt.h
projects/adc_driver/src/main.c

`DerivePointerAlignment: false` so that we use right aligned pointer always.

ELEC-40: Disable Derive Pointer Alignment and Reformat all Files

---

libraries/ms-common/test/test_gpio.c
projects/driver_controls/src/gpio_expander.c
projects/driver_controls/src/x86/ads1015.c

Did a `make reallyclean` `make build_all PLATFORM=x86 COMPILER=clang` and found a few trivial cast errors that needed fixing.

ELEC-40: Fix Clang -Wsign-conversion errors

---

Makefile
libraries/libcore/inc/test_helpers.h
libraries/libcore/rules.mk
libraries/libcore/test/test_mock.c
make/build_test.mk
platform/x86/platform.mk

Adds support for test-specific mocking through the use of GCC's `-Wl,wrap` with an example. Also fixes x86 flash locations for `test_all`.
The idea is that `$(T)_test_[module]_MOCKS := [func names]` can be used to wrap specific functions that need to be mocked, and `TEST_MOCK` wraps the mocked function name. I wanted to add this for validating modules that depend mostly on external hardware. Mocking would allow us to inject arbitrary data and failure conditions without modifying the hardware module itself.

ELEC-378: Support mocking in tests

---

libraries/ms-common/src/x86/can_hw.c

According to [`signal (7)`](http://man7.org/linux/man-pages/man7/signal.7.html), signals are indeterminate in which thread of a particular process they trigger. As a result the CAN TX or RX threads often handled the signal. This isn't good since it can lead to some strange behaviors regarding mutex ownership. To get around this we mask the pthreads individually from receiving signals as they are spawned via [`pthread_sigmask`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_sigmask.html).
Since CAN Hardware is the only location we use pthreads we can limit the change to this module. We could make this a function under `interrupt.h` if we expect it to be more widely used.

ELEC-386: Mask signal handling in CAN RX/TX Threads

---

libraries/ms-common/src/x86/can_hw.c

There was a deadlock between the CAN TX thread and `can_hw_transmit` called from the soft timer signal handler.
> The TX thread is holding the TX mutex while the critical section mutex is held by the main thread in the soft timer signal handler. This causes a deadlock because the TX thread attempts to acquire the critical section mutex to process the FIFO while the main thread attempts to acquire the TX mutex to push data using can_hw_transmit.
This fix removes the TX mutex entirely and replaces it with a semaphore since this is a producer/consumer scenario.

ELEC-386: Fixed x86 CAN HW deadlock

---

projects/chaos/test/test_charger.c

I have no idea how this was passing Travis or on my machine previously. The latest glibc on my machine (as of yesterday) just segfaults when I forget to init timers...

ELEC-105: Fix error in test_charger.c

---

libraries/ms-helper/inc/heartbeat_rx.h
libraries/ms-helper/src/heartbeat_rx.c
libraries/ms-helper/test/test_heartbeat_rx.c

A simple module to register a handler for heartbeats. This simply reduces the heartbeat handling to a single handler which must be registers. In most cases returning `true` from the handler is sufficient (use `heartbeat_rx_auto_ack`). If more complex behavior is required a custom handler can be registered.

ELEC-424: Heartbeat Handler

---

libraries/ms-helper/inc/relay_rx.h
libraries/ms-helper/src/relay_rx.c
libraries/ms-helper/test/test_relay_rx.c

A generic Relay RX module that allows for easy registry of Relay RX handlers which handle a simple single field `uint8_t` CAN message. If the state is valid the registered handler will run. It is expected that the handler will usually trigger one or more GPIO pins although this isn't dictated as it may be useful for other purposes. This is really just a fancy wrapper over `can_register_rx_handler` specialized for the purposes of a relay.
The reason this isn't a simple GPIO pin state over CAN protocol is that some modules may have multiple GPIO pins to trigger or may want to raise an event or save state when the relay changes.

ELEC-423: Relay RX

---

libraries/ms-common/inc/event_queue.h
libraries/ms-common/src/event_queue.c
libraries/ms-common/test/test_event_queue.c
libraries/x86/test/test_x86_cmd.c
projects/driver_controls/src/drive_output.c

This change make the previously priority queue based `event_queue` module into a tiered priority FIFO queue.
The new behavior is as follows:
- `event_raise` is now just a FIFO of `NORMAL` priority.
- `event_raise_priority` allows events to be enqueued into one of five different priority FIFOs: `LOWEST, LOW, NORMAL, HIGH, HIGHEST`.
- `event_process` extracts an event from the highest priority FIFO that contains an event.
- `event_queue_init` is unchanged in it's behavior.
This has affected a single test which is updated with a fix.
It should be noted that CAN should be modified to allow events to be raised into a selected priority of event queue not just the `NORMAL` level (alternatively `HIGH` by default maybe?). This requires widespread changes to lots of locations as `CANSettings` …

ELEC-425: Priority FIFO Event Queue

---

projects/charger/inc/charger_can.h
projects/charger/src/charger_cfg.c
projects/charger/src/charger_controller.c
projects/charger/src/main.c
projects/charger/test/test_charger_controller.c

I found a few minor issues with the charger code in attempting to get it working. This PR fixes those. In particular there were a few oversights with uninitialized memory, or missing inits. Additionally adds configuration for pins. Also the DLC for the CAN message was wrong although it doesn't explain why the charger wasn't responding.

ELEC-451: Fix bugs in charger found during integration attempt

---

libraries/ms-common/src/stm32f0xx/adc.c

Fixes a bug that causes a hardfault in the ADC driver by dividing by 0 when converting.

ELEC-465: Fix hardfault bug in ADC

---

libraries/ms-helper/inc/debug_led.h
libraries/ms-helper/src/debug_led.c
projects/plutus/src/bps_heartbeat.c

Adds a wrapper for the controller board's debug LEDs.
Also adds an example use-case for Plutus. The red LED will turn on when faulting, and the yellow LED represents good ACKs.

ELEC-432: Add debug LED wrapper

---

libraries/stm32f0xx/src/retarget.c
projects/plutus/src/ltc_afe_impl.c

Adds a hardfault handler and replaces the soft timer delay with a busy loop. Soft timers are unstable at very short timeouts.

ELEC-53: Hardfault Handler

---

projects/can_dump/scripts/README.md
projects/can_dump/scripts/can_message.py
projects/can_dump/scripts/dump_system.py
projects/can_dump/scripts/parse_data.py

I'm waiting for the improvements to the CAN script to go in before I rebase
these changes on top of that. However, I'll put this up for review for now,
and then I'll rebase once those changes get in.
This adds a `parse_data.py` script that parses the logged data.
In addition, I've refactored out the CAN parsing logic out of the main 
`dump_system.py` script, and creates a `can_message.py` file that 
contains all that logic. This allows the `parse_data.py` script to share
the code.

ELEC-534: Add CAN dump parser script

---

projects/can_dump/scripts/dump_system.py

This fixes the filename format string so that running on Windows doesn't 
create files with invalid filenames.
Pretty trivial change...

ELEC-546: Fix dump system log filenames

---

projects/can_dump/scripts/dump_system.py

The timestamp has a space, so we should quote this in order to generate CSVs
that can properly be parsed.

ELEC-535: Quote dump_system log timestamps

---

Makefile
README.md
make/filter.mk

Remove the distinction between the `clean` and `reallyclean` targets.
This creates a lot of confusion, and there are very few cases where the
intended behaviour is to only clean a specific project. Moreover, in the
interests of keeping things consistent with typical conventions, this
renames the `reallyclean` target to `clean`.

ELEC-588: Remove reallyclean target

---

libraries/x86/src/x86_socket.c
libraries/x86/test/test_x86_cmd.c

I was messing around with this and I think I fixed it.
I think the issue was that on slow machines the `connect()` happens before the socket is fully initialized (judging by the log output and the solution).
As a fix, when the `connect()` fails, we retry a couple of times. As well, we assert that the `x86_socket_write` actually succeeds. So if the first fix does not work, at least the test will not hang.

ELEC-533: Changed init to retry and assert success

---

projects/fw_tutorial/README.md
projects/fw_tutorial/example/button.c
projects/fw_tutorial/example/config.c
projects/fw_tutorial/inc/button.h
projects/fw_tutorial/inc/config.h
projects/fw_tutorial/inc/potentiometer.h
projects/fw_tutorial/rules.mk
projects/fw_tutorial/src/button.c
projects/fw_tutorial/src/config.c
projects/fw_tutorial/src/main.c
projects/fw_tutorial/src/potentiometer.c
projects/fw_tutorial/test/test_button.c

Module 1 of 2 for the Firmware On-boarding Tutorial (written for the HW Tutorial Board)
Includes:
- Push buttons to control LEDs (example code and exercises)
- ADC to log analog data from potentiometer (not implemented due to hardware issue)
- Unit test and mock function examples

ELEC-622: Firmware Tutorial On-board Module 1

---

libraries/ms-common/src/stm32f0xx/adc.c

ADC is not properly registering its completion of conversions since the introduction of the `conv_complete` boolean. 
- Bench tested on Power Distribution Rev 3
- @g-jessmuir tested on Hardware Tutorial Board

ELEC 634: Fix ADC not completing conversions

---

lint.py

The whitespace/braces case is pretty much handled implicitly by our
clang-format rules. In certain cases, this clashes with the formatting
that clang-format provides, resulting in no way to pass CI.
As a fix, we remove this check from our cpplint.py fork, as we check
that clang-format has been applied on each PR anyways.

ELEC-636: Remove redundant linter case

---

projects/driver_controls_center_console/inc/bps_indicator.h
projects/driver_controls_center_console/src/bps_indicator.c
projects/driver_controls_center_console/src/main.c
projects/driver_controls_center_console/test/test_bps_indicator.c

Add code to drive the BPS Fault Dash Indicator LED by piggybacking the
CAN message used to notify Lights to activate the Strobe. This is
because there's currently some inherent coupling between the Lights
board, which is told when to turn on the Strobe, and the required BPS
Fault Dash Indicator is to reflect that state.
If we wish to process the message slightly faster instead of waiting for
the Driver Controls master board to notify everyone, we could also
listen to the BMS Heartbeat.

ELEC-580: Add Center Console BPS Fault Indicator
