uw-midsun/firmware

Makefile
libraries/lib_test.mk
libraries/library.mk
libraries/unity/README.md
libraries/unity/auto/colour_prompt.rb
libraries/unity/auto/colour_reporter.rb
libraries/unity/auto/generate_config.yml
libraries/unity/auto/generate_module.rb
libraries/unity/auto/generate_test_runner.rb
libraries/unity/auto/parseOutput.rb
libraries/unity/auto/stylize_as_junit.rb
libraries/unity/auto/test_file_filter.rb
libraries/unity/auto/type_sanitizer.rb
libraries/unity/auto/unity_test_summary.py
libraries/unity/auto/unity_test_summary.rb
libraries/unity/auto/unity_to_junit.py
libraries/unity/inc/unity.h
libraries/unity/inc/unity_fixture.h
libraries/unity/inc/unity_fixture_internals.h
libraries/unity/inc/unity_fixture_malloc_overrides.h
libraries/unity/inc/unity_internals.h
libraries/unity/rules.mk
libraries/unity/src/unity.c
libraries/unity/src/unity_fixture.c
platform/stm32f0xx/platform.mk

WIP - added basic unit test support using Unity, enabled LTO for code savings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uw-midsun/firmware/6)

ELEC-31 ELEC-33: Added unit test support

---

.gitignore
project/test_project/main.c

Minor changes to .gitignore to support some python and vim things.
Switched test_project to use ms-common HAL.
TESTED=true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uw-midsun/firmware/7)

ELEC-20 updated gitignore, changed test_project to use HAL

---

lint.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uw-midsun/firmware/8)

ELEC-40 linter support for TODO(TYPE-#): style comments for JIRA tickets.

---

.travis.yml

Add ``.travis.yml`` file for continuous integration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uw-midsun/firmware/12)

ELEC-54: Add .travis.yml file

---

.gitmodules
libraries/ms-common/LICENSE
libraries/ms-common/README.md
libraries/ms-common/inc/event_queue.h
libraries/ms-common/inc/extra_unity.h
libraries/ms-common/inc/fsm.h
libraries/ms-common/inc/fsm_impl.h
libraries/ms-common/inc/gpio.h
libraries/ms-common/inc/misc.h
libraries/ms-common/inc/objpool.h
libraries/ms-common/inc/pqueue.h
libraries/ms-common/inc/status.h
libraries/ms-common/rules.mk
libraries/ms-common/src/event_queue.c
libraries/ms-common/src/fsm.c
libraries/ms-common/src/objpool.c
libraries/ms-common/src/pqueue.c
libraries/ms-common/src/status.c
libraries/ms-common/src/stm32f0xx/gpio.c
libraries/ms-common/src/x86/gpio.c
libraries/ms-common/test/test_event_queue.c
libraries/ms-common/test/test_gpio.c
libraries/ms-common/test/test_objpool.c
libraries/ms-common/test/test_pqueue.c
libraries/ms-common/test/test_status.c

Integrating the ms-common submodule into the main repo.
After this is merged, ms-common will be considered deprecated and should be reference-only.

ELEC-86: Integrate ms-common into main repo

---

libraries/ms-common/test/test_fsm.c

Added basic FSM unit test. Checks the ability to self-cycle, transition between states, output, and fail to transition.

ELEC-45: Added FSM unit test

---

make/build_test.mk

Fix test_all target so it actually runs all the tests. :P

ELEC-79: Fix test_all target

---

libraries/ms-common/inc/event_queue.h
libraries/ms-common/inc/fsm.h
libraries/ms-common/inc/fsm_impl.h
libraries/ms-common/inc/objpool.h
libraries/ms-common/inc/pqueue.h
libraries/ms-common/inc/pqueue_backed.h
libraries/ms-common/src/event_queue.c
libraries/ms-common/src/fsm.c
libraries/ms-common/src/objpool.c
libraries/ms-common/src/pqueue.c
libraries/ms-common/src/pqueue_backed.c
libraries/ms-common/test/test_fsm.c
libraries/ms-common/test/test_objpool.c
libraries/ms-common/test/test_pqueue_backed.c
lint.py
platform/stm32f0xx/platform.mk

Added a backed PQueue implementation and moved objpool's node tracking responsibility.

ELEC-92: Backed PQueue

---

libraries/ms-common/inc/gpio_it.h
libraries/ms-common/src/stm32f0xx/gpio_it.c
libraries/ms-common/src/x86/gpio_it.c
libraries/ms-common/test/test_gpio_it.c

This is the GPIO interrupt API, it is a good example and test of the core interrupt platform libraries. Only one interrupt is available per pin on stm32f0xx.

ELEC-94 GPIO Interrupt API

---

libraries/ms-common/src/objpool.c
libraries/ms-common/src/pqueue.c

Simple change to protect sections and make our data structures atomic. I didn't really think very hard about this one, so let me know if I messed something up. We may want to add some tests to verify that we handle ISRs properly.

ELEC-44: Added critical sections to objpool and pqueue

---

lint.py

Fixed malformed regex for the #endif comment lint category and also applied pylint PEP-8 styling to the file. Blocking ELEC-93 due to CI issues ATM.

ELEC-40 Fix malformed regex

---

libraries/ms-common/inc/fifo.h
libraries/ms-common/inc/objpool.h
libraries/ms-common/src/fifo.c
libraries/ms-common/src/objpool.c
libraries/ms-common/src/pqueue_backed.c
libraries/ms-common/test/test_fifo.c

Implemented a basic FIFO using a ring buffer. I'm planning on using this for UART and CAN.
Tested on x86 and STM32F0xx.

ELEC-179: FIFO

---

libraries/ms-common/inc/delay.h
libraries/ms-common/inc/wait.h
libraries/ms-common/src/delay.c
libraries/ms-common/src/stm32f0xx/wait.c
libraries/ms-common/src/x86/soft_timer.c
libraries/ms-common/src/x86/wait.c
libraries/ms-common/test/test_delay.c

Modules to allow delaying for a set period of time in microseconds, milliseconds or seconds backed by the soft timer module. A wait function is also provided to set the stm32f0xx to wait until an interrupt is triggered.

ELEC-210: Delay and wait module

---

libraries/ms-common/src/stm32f0xx/gpio.c

This change is essentially trivial it just makes some of the OD logic on the stm32f0xx implementation more explicit/clear to the reader. Functionally this is the same as it was before I just used if statements as IMO they are more readable than conditionals and I wasn't comfortable with an implicit cast that was occurring. Feel free to reject this change as it is mainly stylistic.

ELEC-227: Improve readability of GPIO OD logic

---

Makefile
libraries/ms-common/src/pqueue.c
libraries/ms-common/src/x86/can_hw.c

Uses a mutex to signal when to exit. It now has another failure point where the first test doesn't even pass, but we'll see if Travis ever hits it. I'll try to figure it out before I merge.

ELEC-277: x86 Thread Cleanup

---

.travis.yml
Makefile
make/new_target.py

Pretty simple change. Fixed some lint errors in `new_target.py` as well.

ELEC-279: Added pylint to lint target

---

make/new_target.py

Fixes something I thought I'd tested. My bad.

ELEC-282: Fixed new target

---

projects/example/rules.mk
projects/example/src/main.c

I wrote this program during the new member training session for this term and felt it was a relatively simple but effective introduction to some of our libraries and coding style. Moreover, it is relatively easy to port between the discovery board and controller board making it a good first program for people to flash onto a board and modify.
By no means do we have to merge this but I thought it might be a nice example to have available. I know that test_project is a more complex example of this but it doesn't work on the controller board. I wanted something that could readily work on either piece of hardware without much configuration or peripherals.

ELEC-290: Example project for discovery and controller board

---

DEVELOPING.md

Add instructions that cover setup of the Vagrant development environment to develop firmware.

ELEC-242: Add DEVELOPING.md

---

projects/chaos/inc/gpio_seq.h
projects/chaos/rules.mk
projects/chaos/src/gpio_seq.c
projects/chaos/src/main.c
projects/chaos/test/test_gpio_seq.c

Simple PR that allows sequencing of GPIO state changes with delays by looping through arrays. This will be used for the various power sequences required on Chaos such as booting and shutting down the car and transitioning to charging mode. This is relatively generic but will probably only be used by power distribution so there is no need to put it in `ms-common`.

ELEC-105: GPIO sequencing for power distribution

---

projects/driver_controls/src/center_console.c
projects/driver_controls/test/test_mech_brake_calibration.c

I forgot to actually commit mech brake calibration data. With that, mech brake works well @ashraf2047 :)

ELEC-456: Actually commit mech brake calibration

---

projects/chaos/inc/chaos_flags.h
projects/plutus/src/killswitch.c

Fixes issues with the Chaos compile flags.

ELEC-507: Fix compile flags

---

projects/can_dump/scripts/requirements.txt
projects/mc_interface/scripts/dump_motor.py

Add requirements.txt to can_dump project for posterity

ELEC-532: Add can_dump project requirements.txt

---

libraries/ms-common/inc/spi.h
libraries/ms-common/src/stm32f0xx/spi.c

In order to write the SD card driver, the user must have manual control of the CS line. This PR allows users of the SPI driver to manually control the CS line and the receive / transmit flow

ELEC-63: Exposing more functionality to user in the SPI driver
